name: Build and Deploy Hugo Site

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"

            - name: Build site
              run: hugo --minify

            - name: Archive site
              uses: actions/upload-artifact@v4
              with:
                  name: public
                  path: public

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download site artifact
              uses: actions/download-artifact@v4
              with:
                  name: public
                  path: public

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

            - name: Deploy with rsync
              run: rsync -avz --delete ./public/ ${{ secrets.SERVER_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SERVER_WEBROOT }}
